version: "3"
services:
    db:
        container_name: back-end-dev-db
        build:
            context: ../mysql-dev
            dockerfile: ./Dockerfile
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            start_period: 3s
            interval: 1s
            timeout: 1s
            retries: 1000
    app:
        container_name: back-end-dev-app
        build:
            context: ../../
            dockerfile: ./Containers/back-end-dev/Dockerfile
        environment:
            - DB_HOST=back-end-dev-db
            - DB_PORT=3306
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        links:
          - db