version: "3"
services:
    db:
        container_name: mysql-dev-db
        build:
            context: ../mysql-dev
            dockerfile: ./Dockerfile
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root